---
title: "CV | PEDAGOGISK MERITPORTFÖLJ"
author: "Erik Marsja"
address: "Kandidatvägen 1, SE-907 33 Umeå, Sweden"
dob: "1981-05-26"
email: erik.marsja@umu.se
web: www.marsja.se
phone: "090-786 79 59"
github: marsja
output:
  pdf_document:
    latex_engine: pdflatex
    template: template.tex
    keep_tex: no
geometry: margin=1.2in
subparagraph: yes
fontawesome: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pedagogisk grundsyn

Under mina år som doktorand har jag erhållit undervisningserfarenhet, och tagit kurser i universitetspedagogik. Detta har haft en stark påverkan på min utveckling som lärare. Jag reflekterar ofta på min roll som lärare, och är driven till att utveckla och förbättra mina pedagogiska färdigheter. Som resultat av detta spenderar jag ofta mycket tid på att förbereda min undervisning. 


Min syn på kunskap grundas i ämnena jag läst under min tid som grundutbildnings- och forskarstudent; kognitionsvetenskap (särskilt kognitionspsykologi). Det vill säga, min syn är att kunskap baseras på empiriska resultat (Gustafsson, 2002). Min syn har emellertid ändrats till att anse att djupare kunskap även kräver förståelse av fakta. Denna utveckling har sprungit ur min erfarenhet av undervisning, och de pedagogiska kurser jag läst, men även min fördjupning i psykologi som ämne. Jag ha kommit anamma ett synsätt baserat på bland annat Gustaffsons (2002) fyra F; fakta, förståelse, förtrogenhet, och färdighet. 

Eftersom min undervisning, mångt och mycket, har rört sig i början av utbildningen har mitt mål är att studenten ska lära sig att förstå fakta. Jag har emellertid även fått möjligheten att undervisa i ett par kurser med tillämpat fokus, och projektkurser där studenterna ska i kontakt med näringslivet kunna tillämpa den kunskap de lärt sig tidigare. Här har utmaningen varit att stödja dem att tillämpa sina teoretiska kunskaper men även att teoretiskt förstå det praktiska. 


Lärande är för mig en dynamisk process som pågår hela livet ut och handlar sig om att erhålla de fakta, förståelse, förtrogenhet, och färdighet (eller bara fakta och förståelse i många fall inom de ämnen jag undervisar). Lärande är, för mig, väldigt starkt sammankopplat med det psykologiska konstrukt som vi kallar minne (dvs., den process som gör att vi kan lagra och komma ihåg information) men även till beteende.  Med det sagt, så anser jag även att för lärande krävs ett sunt ifrågasättande där, bland annat, kunskap om vikten av källkritik gör att studenter väva in ny kunskap med tidigare erfarenheter. Detta kan i förlängningen förhoppningsvis bidra att studenterna kan omsätta den nya kunskapen i praktik.

Undervisningen har självklart en central roll i lärandet och huvudsyftet för all utbildning är att studenterna uppnår förväntade mål. Det vill säga, undervisning är en målstyrd aktivitet som syftar för att främja studenternas lärande. För att uppnå detta behöver man skapa en bra miljö för studenterna. En bra inlärningsmiljö vilar till stor del på mina pedagogiska färdigheter. Jag anser att mitt uppdrag är inte bara att förmedla kunskap utan jag behöver även skapa en intressant omgivning som stimulerar till lärande. Jag anser att engagemang och entusiasm är väldigt viktigt här eftersom det, enligt min erfarenhet, även visar sig hos studenterna. 

En annan viktig faktor är att skapa en öppen atmosfär där studenterna vågar att ställa frågor. Här är vikten av ett genus- och intersektionellt perspektiv väldigt viktigt att ha i sin undervisning. Förutom en strävan att inrymma dessa perspektiv i undervisningen, vilket i många av de undervisningsmoment jag haft inte alltid är möjligt, så betyder detta även att försöka uppmärksamma och motverka negativa tendenser knutna till kön, sexualitet, etnicitet, funktionsnedsättning och ålder i alla undervisningssammanhang. Jag anser även att det är av stor vikt att arbeta med medvetenhet om dessa perspektiv även i själva planeringsstadiet (exv., gällande studiematerial, gruppövningar, handledning).

## Den pedagogiska praktiken

Genom åren så har jag fått erfarenhet av undervisningsuppdrag i form av föreläsare, handledare, ansvarig för seminarier och gruppövningar, laborationer, samt workshops. Som framgår av bifogat CV har min undervisning på universitetet skett på grund-, och avanceradnivå i en sammanlagd omfattning av ca 950 klocktimmar. Min undervisning har skett för studenter på psykolog-, och tränar, och kognitionsvetarprogrammet, studenter på fristående kurser, internationella studenter (på engelska), samt civilingenjörer. Jag upplever denna mångfald av studerandegrupper som berikande i ett tvärdisciplinärt avseende.

Något som är viktigt för mig är att min undervisning bearbetas och utvecklas. Detta sker i takt med att jag lär mig ny pedagogiska knep och teorier men även när jag upptäcker att studenterna verkar svårigheter med vissa aspekter. Till exempel, jag började föreläsa i perception för snart 3 år sedan. Första föreläsningen höll jag för studenter vid tränarprogrammet. Min första fundering var: i deras framtida yrkesroll, hur kan kunskap om människans perception vara till gagn? Här försökte jag med en rad olika exempel från idrott förmedla att kunskap kring perception kunde förbättra bland annat prestation hos idrottsutövaren. 

Kunskapen jag ville förmedla verkade dock inte helt nå fram. Jag undervisade inte mer på detta program men jag tog med detta in andra föreläsningar: alltid försöka fundera kring varför det är viktigt för studenterna att kunna det jag föreläser om. 
Praktiskt sett har jag än så länge bara tillämpat aspekter av variationsteori (se Ling & Marton, 2012). Jag har försökt kontrastera olika teorier eller synsätt mot varandra så det ska bli lättare för studenterna lära sig detta. Genom att studenterna få bryta ned olika, ibland väldigt lika, teorier och se vad som skiljer dem åt upplever jag att det förenklar deras förståelse.

I en annan kurs, Organisations-, miljö-, och arbetspsykologi (moment 2: Forskningsmetodik), har jag även ämnat att tillämpa de 4 F:n (fakta, förståelse, förtrogenhet, och färdighet). För att nå förtrogenhet och färdighet anser jag att man behöver få arbeta tillämpat med den fakta och förståelse man har fått. Jag har därmed hållit enklare dator-labbar i SPSS där jag först gått igenom det som behöver läras för att sedan studenterna själv fått arbeta med att annat material. I denna kurs har jag vidare också arbetat med examination där studenterna får tillämpa sin kunskap och förståelse av statistik genom att få arbeta med material och finna rätt analys-metod, för att sedan utföra analyser i SPSS. 

Avslutningsvis vill jag förmedla att min utveckling som universitetspedagog går givetvis mot att fortsätta anamma mer pedagogiska teorier och försöka koppla dessa samman med psykologiska teorier på inlärning och lärande. Det som närmast ligger till hand är mer individualistiska synsätt som t.ex., relationell pedagogik (Aspelin, 2011). Eftersom en stor del av min undervisning är handledning så ska jag försöka se om jag når fram till studenter bättre genom att skapa relation och utifrån denna relation ha en interaktion och samverkan. Detta anser jag är väldigt viktigt eftersom jag ofta undervisar för studenter med olika bakgrund såväl som framtidsvisioner. Detta gör att jag i min handledning strävar efter att anpassa mig till grupper, och individerna i grupperna. Här kommer kunskap kring relationell pedagogik till nytta.



## Utvärdering från studenter

Jag har en relativt bred erfarenhet eftersom jag har hållit i föreläsningar, handlett projekt och uppsatser, varit seminarieledare, haft workshops, ansvarig för labbar, och mycket mer (se Tabell 1 i mitt CV för en överblick).

Nedan finnes utvärderingar från psykologprogrammet efter de slutfört kursen Organisations-, miljö-, och arbetspsykologi (moment 2: Forskningsmetodik). Endast frågor relevant till min undervisning i kursen är presenterade:

Fråga 4: Vad tycker du om kvaliteten på datalabbarna?? Resulterade i ett medel på 3,68

Fråga 6: Vad tycker du om det kvalitativa artikelseminariet som ett stöd för ditt lärande? Resulterade i ett medel på 3,47

Fråga 9: Nämn tre saker som du tycker var bra på kursen. (öppen fråga):

  - "Dataövnningarna, upplägget och mängden uppgifter."
  
  - "...Tycker även det har varit bra med datalabbar med ordentliga genomgångar av uppgifterna, det främjar lärandet att få göra analyserna på egen hand med lärare på plats..."
  
  - "Engagerade och pedagogiska lärare - SPSS-momentet med datalab och examination var bra och lärorikt - God kommunikation mellan studenter och lärare"
  
  -"SPSS datalabbar och material var super bra. Variation med film,
  papper å litteratur."
  
  - "1. Bra och nyttigt att vi får lära oss mer om kvalitativ metod...,  ...3. Bra SPSS-övningar till datalabbarna."
  
## Kurser i Universitetspedagogik

 - Introduktionskurs i högskolepedagogik, VT13 (1 vecka heltid), vid Universitetspedagogik och Lärandestöd, Umeå Universitet
 - Undervisning på högskolan, VT15 (1 vecka heltid), vid Universitetspedagogik och Lärandestöd, Umeå Universitet
 - Teorier om lärande, HT16 (3 veckor heltid), vid Universitetspedagogik och Lärandestöd, Umeå Universitet
 
 
## Referenser

Aspelin, J. (2011). Vad är relationell pedagogik? Persson S. (Ed.), *Om relationell pedagogik* (pp. 13-25). Malmö: Gleerups Utbildning AB

Gustavsson, B. (2002). Vad är kunskap? En diskussion om praktisk och teoretisk kunskap. Kalmar: Leanders Grafiska AB.

Ling, L. M., & Marton, F. (2012). Towards a science of the art of teaching: Using variation theory as a guiding principle of pedagogical design. International Journal for Lesson and Learning Studies, 1(1), 7–22. http://doi.org/10.1108/20468251211179678

Säljö, R. (2015). Lärande: En introduktion till perspektiv och metaforer. Malmö: Gleerups
utbildning AB
