---
title: "Curriculum Vitae"
author: Erik Marsja
address: "Kandidatvägen 1, SE-907 33 Umeå, Sweden"
email: erik@marsja.se
web: marsja.se
phone: "+4670-36 33 662"
github: marsja
output:
  pdf_document:
    latex_engine: pdflatex
    template: template.tex
    keep_tex: yes
  word_document: default
subparagraph: yes
fontawesome: yes
date: '`r Sys.Date()`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Education

2017 \hspace{1.5cm}\textbf{Ph.D. in Psychology}
\hrule

\begin{changemargin}{2.3cm}{2.4cm}

Department of Psychology, Umeå University.

\textbf{Thesis title}: Attention capture by sudden and unexpected changes: a multisensory perspective. 
Available from the DiVA Database: http://umu.diva-portal.org/smash/record.jsf?pid=diva2%3A1156775)

\textbf{Supervisors}: Associate Professor Jessica K. Ljungberg, Professor Gregory Neely, \& Dr. Patrik Hansson

\end{changemargin}

2012 \hspace{1.5cm}\textbf{M.Sc. in Cognitive Science}
\hrule
\begin{changemargin}{2.3cm}{2.4cm}


\textbf{Thesis title}: Attention Capture: The Impact of Change in Spatial Sound Source on Behavior. 
    
\textbf{Supervisor}: Associate Professor Jessica K. Ljungberg
    
\end{changemargin}

    
2011 \hspace{1.5cm}\textbf{B.Sc. in Cognitive Science}
\hrule
\begin{changemargin}{2.3cm}{2.4cm}


Department of Psychology, Umeå University.

\textbf{Thesis title}:  Attention Capture: Studying the Distracting Effect of One’s Own Name. 
Available from DiVA Database: http://urn.kb.se/resolve?urn=urn:nbn:se:umu:diva-46607.
    
\textbf{Supervisor}: Associate Professor Jessica K. Ljungberg

\end{changemargin}

## Publications

### International peer-reviewed journals

**Marsja**, E., Neely, G., & Ljungberg, J. K. (2018). Investigating Deviance Distraction and the Impact of the Modality of the To-Be-Ignored Stimuli. Experimental Psychology, 65(2), 61–70. http://doi.org/10.1027/1618-3169/a000390

Ljungberg, K. J., Parmentier, F. B. R., Jones, D. M., **Marsja**, E., & Neely, G. (2014). “What’s in a name?” “No more than when it’s mine own". Evidence from auditory oddball distraction. Acta Psychologica, 150C, 161–166. doi:10.1016/j.actpsy.2014.05.009.

### Publications In Preparation/Submitted/Under Revision

Rosa, E., **Marsja**, E., Ljungberg K.J. (Manuscript in Preparation). Tactile warnings constitute an efficient alarm during high mental workload in simulated flight tasks

Marsh, J.E., Vachon, F., Sörqvist, P., **Marsja**, E., Röer J.P., & Ljungberg, K.J. (Under Revision).  Irrelevant vibro-tactile stimuli produce a changing-state effect: Implications for theories of interference in short-term memory.

**Marsja**, E., Neely, Ljungberg, K.J (Manuscript in Preparation). Deviance distraction in the auditory and tactile modalities after repeated exposure: differential aspects of tactile and auditory deviants.

## Conference Presentations

**Marsja**, E., Marsh, J.E., Neely G., Hansson P., Ljungberg K.J., (2017, April). Domain-generality or domain-specificity of the short-term memory: insights from a multisensory distraction paradigm. Re-thinking the Senses Spring School, Dubrovnik, Croatia. **Poster**.

**Marsja**, E., Marsh, J.E., Neely G., Hansson P., Ljungberg K.J., (2016, September). Do Spatial Changes in Sounds and Vibrations Affect Visuo-spatial and Verbal Short-Term Memory? Attention and Control: Insights from Distraction, Workshop, University of Central Lancashire, Preston, UK. **Invited Talk**.

**Marsja**, E., Marsh, J.E., Neely G., Hansson P., Ljungberg K.J., (2016, June). Spatial Change in Multisensory Distractors Impact on Verbal and Spatial Short Term Memory. International Multisensory Research Forum 17^th^ annual meeting, Suzhou, CHN. **Oral presentation**.

**Marsja**, E., Neely G., Ma, L., Ljungberg K.J., (2015, August). Cross-modality matches of intensity and attention capture dimensions of auditory and vibrotactile stimuli. Fechner Day 2015. The 31^st^ Annual Meeting of the International Society for Psychophysics, Québec, CA. **Poster**.

**Marsja**, E., Neely, G., Parmentier, F.B.R., Ljungberg, K.J., (2014, October) Deviance Distraction Is Contingent on Stimuli Being Presented within the Same Modality. Psychonomic Society’s 55^th^ Annual Meeting. Long Beach, CA, USA. **Poster**.

Ljungberg, K.J., Parmentier, F.B.R., **Marsja**, E., Neely, G., Jones, D., (2014, January). Any Tom, Dick, or Harry will do: Hearing one’s own name distracts no more than any other in a cross-modal oddball task. Experimental Psychology Society Meeting. London, UK. **Poster**.

**Marsja**, E., Neely, G., Parmentier, F.B.R., Ljungberg, K.J., (2013, October). Maintenance of the distractive effect of deviating vibrotactile stimuli in a cross-modal oddball paradigm.  the 29^th^ Annual meeting of the International Society of Psychophysics, Freiburg, DE. **Poster**.

## Funding and Grants

**6000 SEK** from the Department of Psychology, Umeå University, for participating in the Re-thinking the Senses Spring School, Dubrovnik, Croatia, 2017.

**15000 SEK** from Lars Hiertas Minnesfond for the project *Är korttidsminnet domän-generellt eller domän-specifikt? (Is short-term memory domain-general or domain specific?)*, 2016.

**12 000 SEK** from the Faculty of Social sciences, Umeå University, for participating in the workshop Attention and Control: Insights from Distraction and visiting a researcher at the University of Central Lancashire, Preston, UK, 2016. 

**8000 SEK** from the Department of Psychology, Umeå University, for participating the conference 17^th^ International Multisensory Research Forum 15-18 June, Souzou, China, 2016.

**10 000 SEK**  from JC Kempes minnesfond for the project *Is everyday distractibility related to attention capture by
vibrating deviants?*, 2014.

**9 000 SEK**  from Knut och Alice Wallenbergs Stiftelse for participating in the conferences Psychonomic Society’s 55^th^ Annual Meeting, 20-23 November, and APCAM, 20 November, Long Beach, USA, 2014. 

**6000 SEK** from the Department of Psychology for participating the conference Fechner Day 2013 (the 29^th^ Annual Meeting of the International Society for Psychophysics) 21-25 October, Freiburg i.Br., Germany, 2013.


## Teaching Experience

### Past & current areas at undergraduate level at Umeå University

Primarily in:

* Attention
* Perception
* Applied Cognitive Psychology
* Cognitive Psychology
* Research Methods

Lectures, seminars, lab demonstrations, supervision of group project (both involving empirical and applied projects) and supervision of thesis' have been given at the Department of Psychology Umeå University, Sweden. I have so far taught 950 clock hours. 


### Supervision of Master students (graduate level)


Ma, L. (2015). Department of Psychology, Umeå University. "Cross-Modal Matching of Distractibility in Auditory and Tactile Stimuli". Master Thesis in Cognitive Science (15 ECTS).

Blide, M. (2014). Department of Psychology, Umeå University. "Att orka lämna ett misshandelsförhållande: Anknytningens beydelse (To cope leaving abusive relationships: The importance of attachment). Master Thesis in Clinical Psychology (30 ECTS).


## Additional skills


* Good skills in Microsoft Word and Excel
* Good skills in statistical software such as SPSS and R
* Good programming skills in Python (v2.7.x) and R
* Basic programming skills in Visual Basic, E-basic (E-prime), and MATLAB
* Basic skills in Markdown (e.g., RMarkdown) and \LaTeX
* Programming and performing experiments using both E-prime, MATLAB, and Python (i.e., PsychoPy, OpenSesame, & Expyriment)

### Responsibilities

* Elected chairperson of the Ph.D. students Council of the Department of Psychology, Umeå University.
