---
output:
  word_document: default
  html_document: default
  pdf_document: default
---

## Peer-reviewed Original Studies
Stenbäck, V., **Marsja**, E., Ellis, R., Rönnberg, J. (2022). Relationships between behavioural and self-report measures in speech recognition in noise recognition in noise. *International Journal of Audiology*. [https://doi.org/10.1080/14992027.2022.2047232](https://doi.org/10.1080/14992027.2022.2047232)

**Marsja**, E., Stenbäck, V., Moradi, S., Danielsson, H., & Rönnberg, J. (2022). Is Having Hearing Loss Fundamentally different? Multi-group structural equation modeling of the effect of cognitive functioning on speech identification. *Ear and Hearing*. [https://doi.org/10.1097/AUD.0000000000001196](https://doi.org/10.1097/AUD.0000000000001196) [(PDF)](https://bit.ly/EANDH22)

Stenbäck, V., **Marsja**, E., Hällgren, M., Lyxell, B., & Larsby, B. (2021). The Contribution of Age, Working Memory Capacity, and Inhibitory Control on Speech Recognition in Noise in Young and Older Adult Listeners. *Journal of Speech, Language, and Hearing Research, 64*(11), 4513–4523. [https://doi.org/10.1044/2021_JSLHR-20-00251](https://doi.org/10.1044/2021_JSLHR-20-00251)

Rosa, E., **Marsja**, E., & Ljungberg, J. K. (2020). Exploring Residual Capacity: The Effectiveness of a Vibrotactile Warning During Increasing Levels of Mental Workload in Simulated Flight Tasks. *Aviation Psychology and Applied Human Factors, 10*(1), 13–23. [https://doi.org//10.1027/2192-0923/a000180](https://doi.org//10.1027/2192-0923/a000180)

**Marsja**, E., Marsh, J.E., Hansson, P., & Neely, G. (2019). Examining the Role of Spatial Changes in Bimodal and Uni-Modal To-Be-Ignored Stimuli and How They Affect Short-Term Memory Processes. *Frontiers In Psychology*. [https://doi.org/10.3389/fpsyg.2019.00299](https://doi.org/10.3389/fpsyg.2019.00299) [(PDF)](https://bit.ly/3LkKD19)

**Marsja**, E., Neely, G., & Ljungberg, K.J. (2018). Investigating Deviance Distraction and the Impact of the Modality of the To-Be-Ignored Stimuli. *Experimental Psychology, 65*(2), 61–70. [http://doi.org/10.1027/1618-3169/a000390](http://doi.org/10.1027/1618-3169/a000390) [(Skript och data tillgängligt: https://osf.io/amd2h/.)](https://osf.io/amd2h/.)

Ljungberg, K. J., Parmentier, F. B. R., Jones, D. M., **Marsja**, E., & Neely, G. (2014). “What’s in a name?” “No more than when it’s mine own". Evidence from auditory oddball distraction. *Acta Psychologica, 150C*, 161–166. [http://dx.doi.org/10.1016/j.actpsy.2014.05.009](http://doi.org/10.1027/1618-3169/a000390)

## Conference Contributions

**Marsja**, E., Danielsson, H., Stenbäck, V., Moradi, S., Rönnberg, J. (2019, November). Examining how Cognitive Functioning, Aging, and Hearing Loss, Affect Speech-in-Noise Performance. Aging and Speech Communication conference, Tampa, Florida, USA. **Poster**.

Stenbäck, V., **Marsja**, E., Danielsson, H., Rönnberg, J. (2019, November). Logical and Auditory Inference Making: Performance in the HINT in normally-hearing and hearing-impaired listeners. Aging and Speech Communication conference, Tampa, Florida, USA. **Poster**.

Bampouni, E., **Marsja**, E., Sörman, D.E., & Ljungberg, K.J (2019, November). Do Action Gamers Have Enhanced Visual Search Skills? a Realistic Task Approach. The 15th SweCog conference of the Swedish Cognitive Science Society, Umeå, Sweden. **Poster**. 

**Marsja**, E., Danielsson, H., Stenbäck, V., Moradi, S., & Rönnberg, J. (2019, June). Examining Relationship Amongst Cognition,
Hearing Loss, Age, & Speech in Noise. Cognitive Hearing Science for Communication, Linköping, Sweden. **Poster**.

Stenbäck, V., Moradi, S., **Marsja**, E., Danielsson, H., & Rönnberg, J. (2019, June). Logical and auditory inference-making in normally-hearing and hearing-impaired listeners. Cognitive Hearing Science for Communication, Linköping, Sweden. **Poster**.

**Marsja**, E., Marsh, J.E., Neely G., Hansson P., & Ljungberg K.J. (2017, April). Domain-generality or domain-specificity of the short-term memory: insights from a multisensory distraction paradigm. Re-thinking the Senses Spring School, Dubrovnik, Croatia. **Poster**.

**Marsja**, E., Marsh, J.E., Neely G., Hansson P., & Ljungberg K.J. (2016, September). Do Spatial Changes in Sounds and Vibrations Affect Visuo-spatial and Verbal Short-Term Memory? Attention and Control: Insights from Distraction, Workshop, University of Central Lancashire, Preston, UK. **Invited presentation**.

**Marsja**, E., Marsh, J.E., Neely G., Hansson P., & Ljungberg K.J. (2016, June). Spatial Change in Multisensory Distractors Impact on Verbal and Spatial Short Term Memory. International Multisensory Research Forum 17^th^ annual meeting, Suzhou, CHN. **Oral presentation**.

**Marsja**, E., Neely G., Ma, L., & Ljungberg K.J., (2015, August). Cross-modality matches of intensity and attention capture dimensions of auditory and vibrotactile stimuli. Fechner Day 2015. The 31^st^ Annual Meeting of the International Society for Psychophysics, Québec, CA. **Poster**.

**Marsja**, E., Neely, G., Parmentier, F.B.R., & Ljungberg, K.J. (2014, October) Deviance Distraction Is Contingent on Stimuli Being Presented within the Same Modality. Psychonomic Society’s 55^th^ Annual Meeting. Long Beach, CA, USA. **Poster**.

Ljungberg, K.J., Parmentier, F.B.R., **Marsja**, E., Neely, & G. Jones, D., (2014, January). Any Tom, Dick, or Harry will do: Hearing one’s own name distracts no more than any other in a cross-modal oddball task. Experimental Psychology Society Meeting. London, UK. **Poster**.

**Marsja**, E., Neely, G., Parmentier, F.B.R., & Ljungberg, K.J. (2013, October). Maintenance of the distractive effect of deviating vibrotactile stimuli in a cross-modal oddball paradigm.  The 29^th^ Annual meeting of the International Society of Psychophysics, Freiburg, DE. **Poster**.